<a href="https://colab.research.google.com/github/werowe/Auth0/blob/main/games/cuda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numba import vectorize

@vectorize(['float32(float32, float32)'], target='cuda')
def Add(a, b):
  return a + b

# Initialize arrays
N = [10000,10]
A = np.ones(N, dtype=np.float32)
B = np.ones(A.shape, dtype=A.dtype)
C = np.empty_like(A, dtype=A.dtype)

# Add arrays on GPU
C = Add(A, B)
print(C)

[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]


/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 98 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


In [ ]:
# https://stackoverflow.com/questions/63176971/filling-out-numpy-array-in-parallel

In [ ]:
C.shape

In [16]:
#works

import numpy as np
from numba import vectorize

@vectorize(["float32(float32, float32)"], target='cuda')
def f(a,b):

  for i in range(10000):
    a=b
    
  return b


a = np.zeros((10000,10), dtype=np.float32)
b = np.zeros((10000,10), dtype=np.float32)

f(a,b)

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 98 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [54]:
import numpy as np
from numba import vectorize

@vectorize(["void(float32, float32)"], target='cuda')
def f(a,b):

  for i in range(10000):
    a=4*b
  return b


a = np.ones((10000,10), dtype=np.float32)
b = np.random.rand(10000,10).astype('f')

f(a,b)

/usr/local/lib/python3.10/dist-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 98 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))


array([[0.17187412, 0.638744  , 0.9411341 , ..., 0.9963005 , 0.38301   ,
        0.1056145 ],
       [0.8587181 , 0.7049687 , 0.3086888 , ..., 0.7010578 , 0.48395935,
        0.9546782 ],
       [0.60322917, 0.6282003 , 0.7860869 , ..., 0.46414292, 0.641431  ,
        0.5890902 ],
       ...,
       [0.25970846, 0.91552156, 0.59626096, ..., 0.2289193 , 0.00695293,
        0.180941  ],
       [0.6803259 , 0.6008099 , 0.86902815, ..., 0.6271602 , 0.22071159,
        0.16530712],
       [0.26526394, 0.06113506, 0.39858928, ..., 0.62779665, 0.44882658,
        0.03787582]], dtype=float32)

In [45]:
a[1].shape

(10,)